Default: &defaults
  database: aliostodo.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: aliostodo_test.sqlite3
  <<: *defaults

Staging:
  database: aliostodo_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: aliostodo_production.sqlite3
  poolsize: 100
  <<: *defaults
